debugMode: true
port: 50052

influxdbServer: PUT_SERVER_IP_HERE
influxdbPort: PUT_SERVER_PORT_HERE
influxdbUsername: PUT_DB_USER_HERE
influxdbPassword: PUT_DB_USER_PASSWORD_HERE
waitDuration: 2 # seconds

jwtServerTimeout: 5000 #milliseconds
jwksServerEndpoint: PUT_JWKS_URL_HERE
jwksCheckServerCertificate: false

influxdbDBNameMap:
  CMX_LQLS26:
  - Zack_CMX_LQLS26
  - autogen
  XXC_MBXSLL:
  - Kelly_XXC_MBXSLL
  - autogen
  CMS_LJ3Z4P:
  - Slater_CMS_LJ3Z4P
  - autogen
