debugMode: true
port: 50052

influxdbServer: 
influxdbPort: 
influxdbUsername: 
influxdbPassword: 
waitDuration: 2 # seconds

jwtServerTimeout: 5000 #milliseconds
jwksServerEndpoint: 
jwksCheckServerCertificate: false

influxdbDBNameMap:
  CMX_LQLS26:
  - Zack_CMX_LQLS26
  - autogen
  XXC_MBXSLL:
  - Kelly_XXC_MBXSLL
  - autogen
  CMS_LJ3Z4P:
  - Slater_CMS_LJ3Z4P
  - autogen
